syntax on           " Turn syntax highlighting on

filetype on		    " Enable type file detection
filetype plugin on	" Enable plugins and load plugin for the detected file type
filetype indent on	" Load an indent file for the detected file type

set number		    " Show line numbers
set nowrap		    " Wrap lines
set showmatch		" Highlight matching brace
set nocompatible	    " Disable compatibility with vi
 
set hlsearch		    " Highlight all search results
set incsearch		" Searches for strings incrementally
set smartcase		" Enable smart-case search
set ignorecase		" Always case-insensitive
 
set smarttab		    " Enable smart-tabs
set expandtab		" Use spaces instead of tabs
set softtabstop=4	" Number of spaces per Tab

set autoindent		" Auto-indent new lines
set smartindent		" Enable smart-indent
set shiftwidth=4	    " Number of auto-indent spaces
 
set ruler			            " Show row and column ruler information
set undolevels=1000		        " Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour

set wildmenu                " Enable auto completion menu after pressing TAB
set wildmode=list:longest   " Make wildmenu behave like similar to Bash completion
