#!/bin/bash

# ANSI color variables (BOLD)
NColor='\033[0m'      # No Color
BRed='\033[1;31m'     # Red
BGreen='\033[1;32m'   # Green
BYellow='\033[1;33m'  # Yellow

# applications directory
DIR=/usr/share/applications
# .desktop to remove
DESKTOPS="avahi-discover.desktop bvnc.desktop bssh.desktop qv4l2.desktop qvidcap.desktop qt5ct.desktop qt6ct.desktop libreoffice-startcenter.desktop ardour9.desktop lstopo.desktop com.cloudflare.WarpTaskbar.desktop"

echo -e "\n${BYellow}changing directory to \"$DIR\"...${NColor}"
cd $DIR
echo -e "${BGreen}done.${NColor}"

echo -e "\n${BYellow}removing desktop entries...${NColor}"
sudo rm -f $DESKTOPS
echo -e "${BGreen}done.${NColor}\n"
